### ISSUE TITLE
Broken image Banner.png

### ISSUE THREAD

**Issue by lex111** [onmyway133/fantastic-ios-architecture#6]

**Comment by onmyway133** [comment]
@lex111 Hi, can you check it again, the banner still displays fine

![banner](https://user-images.githubusercontent.com/2284279/30737301-6e421ac6-9f86-11e7-9db6-933d21fad02d.png)

**Comment by lex111** [comment]
Yea, the image is displayed correctly, my ad blocker blocked this image,  sorry about that :/
